strict_mode = false
sort_order = ["tmux", "tmuxinator", "config", "zoxide"]
dir_length = 3


[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "aws-governance "
path = "~/projects/aws-governance"

[[session]]
name = "Dotfiles ⚙️"
path = "~/projects/dotfiles"


[[session]]
name = "findings automation "
path = "~/projects/findings-automation"

[[session]]
name = "cdk-hybrid-environments "
path = "~/projects/cdk-hybrid-environments"

