alias coo_python='python3 -m cookiecutter $HOME/cookiecutter/cookiecutter-pypackage -o $HOME/Projects'
alias coo_golang='python3 -m cookiecutter $HOME/cookiecutter/cookiecutter-golang -o $HOME/go/src'
alias tmp_mk='cd $(mktemp -d -t deleteme.XXX)'
alias tmp_clean='rm -rf /tmp/deleteme*)'
alias do_prune_everything='docker system prune -a'
alias git_rollback_to_remote='git reset --hard @{u}'
alias git_rm_ignored='git rm -r --cached . && git add . && git commit -m "purged files based on new gitignopre fix"'